### ISSUE TITLE
install figaro to add aws keys to application.yml (Venel has to do this, since he has the aws key)

### ISSUE THREAD

**Issue by Peterortiz82** [venelrene/TheHatGame#8]
ArgumentError: aws_access_key_id, aws_secret_access_key is because the aws_key is not set properly. It may be set on venel's local machine, but anyone else trying to install or use a rake command will come across this error. You don't want to share information like that on github or with others, so I believe figaro is the best way to set this up. You might want to look into it more, but I'm pretty sure that's what's needs to be done. That's why John can't install devise properly. I tried to run a migration and got the same error. Check this link out [stackoverflow](http://stackoverflow.com/questions/25596504/missing-required-arguments-aws-access-key-id-aws-secret-access-key) and here's the link to the figaro gem [figaro](https://github.com/laserlemon/figaro).

**Comment by cato-hga** [comment]
Venel was missing the dotenv-rails gem and the .env file. We're good to go now. Thanks!
